#!/bin/bash
set -ex

for target in druidoo druidoo-e; do
    docker image build \
        --file "$DOCKER_TAG.Dockerfile" \
        --build-arg VCS_REF="$GIT_SHA1" \
        --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
        --build-arg BASETAG=${target//druidoo/odoo} \
        --tag "$DOCKER_REPO:$DOCKER_TAG.$target" \
        .
done
